version: '3.1'

services:
  was:
    image: tomcat:9.0
    container_name: mw-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bs_server:5432/bs
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
  
  db:
    image: postgres:16.1
    container_name: mw_db
    environment:
      POSTGRES_DB: bs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - minwook-net
      
networks:
  minwook-net:
    driver: bridge
