version: '2'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bs
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    networks :
      - minwook-net

  db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: bs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks :
      - minwook-net
      
networks:
  minwook-net:
    driver: bridge
