services:
  was:
    image: tomcat:9.0
    container_name: mw-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes :
      - ./target/MW.war:/usr/local/tomcat/webapps/MW.war
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://mw-db:5432/bs
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - minwook-net
  
  db:
    image: postgres:16.1
    container_name: mw-db
    environment:
      POSTGRES_DB: bs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - minwook-net
      
networks:
  minwook-net:
    driver: bridge
